# Generated by Django 2.2.11 on 2023-05-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0355_auto_20230512_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcerequest',
            old_name='orgin_facility',
            new_name='origin_facility',
        ),
        migrations.RenameField(
            model_name='shiftingrequest',
            old_name='orgin_facility',
            new_name='origin_facility',
        ),
    ]
