# Generated by Django 2.2.11 on 2023-05-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0355_auto_20230512_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientconsultation',
            name='HBA1C',
        )
    ]
